name: collect
description: "A Flutter package providing reusable UI components, type extensions, custom types and Material 3 theming support."
version: 0.0.1
homepage: https://github.com/Seb2104/collect
repository: https://github.com/Seb2104/collect

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  unicode: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.recollect.collect
        pluginClass: collectPlugin
      windows:
        pluginClass: collectPluginCApi