name: collect
description: "A Flutter package providing reusable UI components, type extensions, custom types and Material 3 theming support."
version: 1.2.2
homepage: https://github.com/Seb2104/collect
repository: https://github.com/Seb2104/collect

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  unicode: ^1.1.9
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AppleColorEmoji
      fonts:
        - asset: assets/fonts/AppleColorEmoji.ttf

    - family: CrimsonPro
      fonts:
        - asset: assets/fonts/CrimsonPro-VariableFont_wght.ttf
        - asset: assets/fonts/CrimsonPro-Italic-VariableFont_wght.ttf
          style: italic

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/DMSans-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/IBMPlexSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic

    - family: MontaguSlab
      fonts:
        - asset: assets/fonts/MontaguSlab-VariableFont_opsz,wght.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf

    - family: ReCollectIcons
      fonts:
        - asset: assets/fonts/ReCollectIcons.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf
        - asset: assets/fonts/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
          style: italic

    - family: KaTeX_AMS
      fonts:
        - asset: assets/fonts/KaTeX_AMS-Regular.ttf

    - family: KaTeX_Caligraphic
      fonts:
        - asset: assets/fonts/KaTeX_Caligraphic-Regular.ttf
        - asset: assets/fonts/KaTeX_Caligraphic-Bold.ttf
          weight: 700

    - family: KaTeX_Fraktur
      fonts:
        - asset: assets/fonts/KaTeX_Fraktur-Regular.ttf
        - asset: assets/fonts/KaTeX_Fraktur-Bold.ttf
          weight: 700

    - family: KaTeX_Main
      fonts:
        - asset: assets/fonts/KaTeX_Main-Regular.ttf
        - asset: assets/fonts/KaTeX_Main-Bold.ttf
          weight: 700
        - asset: assets/fonts/KaTeX_Main-Italic.ttf
          style: italic
        - asset: assets/fonts/KaTeX_Main-BoldItalic.ttf
          weight: 700
          style: italic

    - family: KaTeX_Math
      fonts:
        - asset: assets/fonts/KaTeX_Math-Italic.ttf
          style: italic
        - asset: assets/fonts/KaTeX_Math-BoldItalic.ttf
          weight: 700
          style: italic

    - family: KaTeX_SansSerif
      fonts:
        - asset: assets/fonts/KaTeX_SansSerif-Regular.ttf
        - asset: assets/fonts/KaTeX_SansSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/KaTeX_SansSerif-Italic.ttf
          style: italic

    - family: KaTeX_Script
      fonts:
        - asset: assets/fonts/KaTeX_Script-Regular.ttf

    - family: KaTeX_Size1
      fonts:
        - asset: assets/fonts/KaTeX_Size1-Regular.ttf

    - family: KaTeX_Size2
      fonts:
        - asset: assets/fonts/KaTeX_Size2-Regular.ttf

    - family: KaTeX_Size3
      fonts:
        - asset: assets/fonts/KaTeX_Size3-Regular.ttf

    - family: KaTeX_Size4
      fonts:
        - asset: assets/fonts/KaTeX_Size4-Regular.ttf

    - family: KaTeX_Typewriter
      fonts:
        - asset: assets/fonts/KaTeX_Typewriter-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.recollect.collect
        pluginClass: collectPlugin
      windows:
        pluginClass: collectPluginCApi