name: collect
description: "The Developers Repertoire"
version: 2.1.0
homepage: https://github.com/Seb2104/collect
repository: https://github.com/Seb2104/collect
topics:
  - extensions
  - utilities
  - widgets
  - datatypes
  - functions

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  unicode: ^1.1.9
  file_picker: ^10.3.10
  system_fonts: ^1.0.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: com.recollect.collect
        pluginClass: collectPlugin
      windows:
        pluginClass: collectPluginCApi